export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const ADD_TO_WALLET = 'ADD_TO_WALLET';
export const ADD_MULTIPLE_TO_WALLET = 'ADD_MULTIPLE_TO_WALLET';
export const REMOVE_FROM_WALLET = 'REMOVE_FROM_WALLET';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const CLEAR_WALLET = 'CLEAR_WALLET';
export const TOGGLE_WALLET = 'TOGGLE_WALLET';