export const ADD_TO_WALLET = 'ADD_TO_WALLET';
export const ADD_MULTIPLE_TO_WALLET = 'ADD_MULTIPLE_TO_WALLET';
export const REMOVE_FROM_WALLET = 'REMOVE_FROM_WALLET';
export const UPDATE_WALLET_QUANTITY = 'UPDATE_WALLET_QUANTITY';
export const CLEAR_WALLET = 'CLEAR_WALLET';
export const TOGGLE_WALLET = 'TOGGLE_WALLET';