export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const ADD_TO_PASSPORT = 'ADD_TO_PASSPORT';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_PASSPORT = 'REMOVE_FROM_PASSPORT';
export const UPDATE_PASSPORT = 'UPDATE_PASSPORT';
export const CLEAR_PASSPORT = 'CLEAR_PASSPORT';
export const TOGGLE_PASSPORT = 'TOGGLE_PASSPORT';